spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/projbanktrastn
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

jwt.secret=H2sfzVFKMCdYKCoq91N2o85SVajQ62zt
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000